### ISSUE TITLE
Automatic glTF to glB conversion

### ISSUE THREAD

**Issue by Qaomen** [Zemanzo/web-marbles#156]
**Description**
Both `*.gltf` and `*.glb` (aka binary glTF) are supported, but the latter has a smaller size. We should automatically convert imported glTF files to glB to save on file size in level files.

**Minimum Acceptance Criteria**
- [ ] Models can be imported both as glTF and glB. (Redundant but should stay the same).
- [ ] Imported models that are of glTF file type should automatically be converted to glB and saved in the project file as such.

**Is blocked by the following issues**
Blocked by #102

**Comment by Zemanzo** [comment]
Scrapping this issue, and instead opting to write a guide on best level-making practices (see #43)
