### ISSUE TITLE
Shadows and render improvements

### ISSUE THREAD

**Issue by Zemanzo** [Zemanzo/web-marbles#177]
**Description**
Shadows would make this thing look a lot better, but they can be rough on performance so we have to make sure things will keep running smoothly.

**Minimum Acceptance Criteria**
- [x] Disable `.matrixAutoUpdate` on meshes by default in the client (since they're all static anyway)
- [x] Enable shadow receiving on meshes by default
- [x] Enable meshes casting shadows by default

**Comment by Qaomen** [comment]
One thing to note is that marbles don't receive shadows by default yet.
