### ISSUE TITLE
Demo or preview?

### ISSUE THREAD

**Issue by briantbutton** [Zemanzo/web-marbles#221]
This looks very interesting!  All I have it the image.  Is there a video or a demo running somewhere?  I would like to check it out.

Sorry if I overlooked the answer to this.

**Comment by Sanquinary** [comment]
Welcome! The live version is always running from the `master` branch. You can test it anytime here:
https://playmarbl.es/client

It is currently running version [Alpha v1.2.0](https://github.com/Zemanzo/web-marbles/releases/tag/v1.2.0)

**Comment by Zemanzo** [comment]
@Sanquinary is correct. We hadn't published the URL here because we didn't want it to be public yet. Since that decision, many improvements have been made and we're ready to at least publish the link here. Thanks for bringing it to our attention, and welcome!
