### ISSUE TITLE
HUD Notifications block camera buttons

### ISSUE THREAD

**Issue by Qaomen** [Zemanzo/web-marbles#250]
**Expected behavior**
HUD notifications will keep to their darn selves!

**Actual behavior**
The left and right sides outside of the HUD notifications will block overlay buttons by overlapping them, even though it doesn't appear to block them. Only the camera style buttons are affected due to their positioning, and the issue disappears once the HUD notifications are gone.

**Reproduction steps**
1. Load the client page.
2. Wait for HUD notifications appear (e.g. the loading/loaded notifs).
3. Try to click the camera buttons while the notification is visible.

**Additional context**
There's probably a more graceful and desirable way to fix this other than re-ordering the overlay elements, so I prefer to leave it to someone who knows said pretty and clean fix (unless they're fine with the re-arranging stuff).

**Comment by Zemanzo** [comment]
Easy fix, just add `pointer-events: none` in the CSS. (Wink wink, nudge nudge @Sanquinary)
