### ISSUE TITLE
Model instancing research

### ISSUE THREAD

**Issue by Zemanzo** [Zemanzo/web-marbles#28]
**Description**
Look into feasibility of instancing models (both marbles & set pieces), as seen in this demo https://threejs.org/examples/#webgl_interactive_instances_gpu

**Minimum Acceptance Criteria**
A grounded reason why or why not to use instances

**Comment by Zemanzo** [comment]
Maybe merge this issue with #29 ?

**Comment by Qaomen** [comment]
Merged with #29
