### ISSUE TITLE
Alternative compression methods

### ISSUE THREAD

**Issue by Qaomen** [Zemanzo/web-marbles#37]
**Description**
In order to keep file size small, we want to use compression for level data. Pako is currently in use, but we should test whether this is the most suitable compression implementation.

**Minimum acceptance criteria**
Research should be done regarding implementations we could use. The most suitable one should be implemented.

**Comment by Zemanzo** [comment]
Changed to [pako](http://nodeca.github.io/pako/) as of #62, requires testing.
