### ISSUE TITLE
Game viewport does not resize with browser viewport

### ISSUE THREAD

**Issue by Zemanzo** [Zemanzo/web-marbles#68]
**Expected behavior**
When resizing the browser viewport, the game viewport should resize accordingly (shrink when smaller, grow when larger)

**Actual behavior**
The game viewport remains at the size it initialized on, causing overflowing or space not being utilized.

**Reproduction steps**
1. Go to /client
2. Resize the browser viewport

**Comment by Qaomen** [comment]
The same thing happens for the editor, so I've added the label for it.
