### ISSUE TITLE
Refactor: Renderer

### ISSUE THREAD

**Issue by Qaomen** [Zemanzo/web-marbles#69]
**Description**
Currently, both the client and editor have their own renderer script in their own respective folders. Portions of it are identical to one another while other parts are client- or editor-specific. The base renderer code should be split and brought under a new `render` folder that both the client and editor will use.

**Minimum Acceptance Criteria**
- There should be a `src/client/render` folder containing the renderer-related script(s).
- Any code specific to the client or editor (e.g. the grid in the editor) should be moved into their relevant scripts in `src/client/client` or `src/client/editor`.
- The renderer code should follow the [Style Guide](https://github.com/Zemanzo/web-marbles/wiki/Style-guide).
- Existing WebGL warnings should be resolved, if possible.

**Is blocked by the following issues**
Although not blocked or directly related, #68 could be taken into account during the refactor.

**Comment by kvanderkamp** [comment]
WebGL errors are not handled.
In my browser WebGL is unavailable, resulting in the marbles client page remaining pink.
Console stack trace:
```
THREE.WebGLRenderer: Error creating WebGL context. three.module.js:22613
    WebGLRenderer three.module.js:22613
    init render.js:19
    js client.js:11
```

https://get.webgl.org/ does handle this error and displays the following message:
> Hmm. While your browser seems to support WebGL, it is disabled or unavailable. If possible, please ensure that you are running the latest drivers for your video card.
> [For more help, please click this link.](https://support.mozilla.org/en-US/kb/upgrade-graphics-drivers-use-hardware-acceleration?redirectlocale=en-US&redirectslug=how-do-i-upgrade-my-graphics-drivers)
