### ISSUE TITLE
Research chunked terrain physics

### ISSUE THREAD

**Issue by Zemanzo** [Zemanzo/web-marbles#77]
**Description**
The ability to cut up the terrain physics collider to reduce the total size of the map file, and gain the ability to have different resolutions of physics detail (e.g. high detail on the track, low detail along the rest of the map)

**Minimum Acceptance Criteria**
Whether it is possible to use chunked terrain physics and if yes, a general idea on how to implement it

**Comment by Qaomen** [comment]
We won't be supporting height fields with dynamic resolution: They are generally loaded from an image (meaning a fixed distance on the grid, each pixel representing the amount of elevation), and the physics library that we use only supports standard height fields.
Terrains loaded as models will still be usable as colliders, only as concave collision shapes. Terrains loaded as image may be supported in the future.
